/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Books.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Books.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube040.bufferGeometry} material={materials['Material.008']} position={[0.868, 21.034, -1.466]} rotation={[-1.315, -0.107, -0.397]} scale={5.738} />
      <mesh geometry={nodes.Cube046.bufferGeometry} material={materials['Material.021']} position={[-0.898, 19.211, -1.203]} rotation={[0.301, -0.395, 0.116]} scale={[5.874, 0.164, 5.738]} />
      <group position={[0.823, 24.685, -4.188]} rotation={[-1.308, -0.101, -0.394]} scale={[6.238, 4.484, 6.238]}>
        <mesh geometry={nodes.Cube052.bufferGeometry} material={materials['Material.021']} />
        <mesh geometry={nodes.Cube052_1.bufferGeometry} material={materials['Material.015']} />
      </group>
      <mesh geometry={nodes.Cube048.bufferGeometry} material={materials['Material.015']} position={[0.142, 26.025, -0.155]} rotation={[-1.315, -0.107, -0.397]} scale={4.898} />
      <mesh geometry={nodes.Cube054.bufferGeometry} material={materials['Material.021']} position={[-1.424, 24.468, 0.069]} rotation={[0.301, -0.395, 0.116]} scale={[5.014, 0.14, 4.898]} />
      <group position={[0.103, 29.141, -2.479]} rotation={[-1.308, -0.101, -0.394]} scale={[5.325, 3.828, 5.325]}>
        <mesh geometry={nodes.Cube060.bufferGeometry} material={materials['Material.021']} />
        <mesh geometry={nodes.Cube060_1.bufferGeometry} material={materials['Material.015']} />
      </group>
      <mesh geometry={nodes.Cube056.bufferGeometry} material={materials['Material.010']} position={[-0.508, 30.31, 0.992]} rotation={[-1.315, -0.107, -0.397]} scale={4.194} />
      <mesh geometry={nodes.Cube062.bufferGeometry} material={materials['Material.021']} position={[-1.884, 28.95, 1.184]} rotation={[0.301, -0.395, 0.116]} scale={[4.294, 0.12, 4.194]} />
    </group>
  )
}

useGLTF.preload('/Books.gltf')
